{{/*
  Create a Secret for Cloudflare credentials.
  Priority: credentials.* (CNAP proxy) > cloudflare.* (standalone)
  Skipped if cloudflare.existingSecret is set.
*/}}
{{- $accountId := .Values.credentials.accountId | default .Values.cloudflare.accountId }}
{{- $token := .Values.credentials.token | default .Values.cloudflare.apiToken }}
{{- $apiBaseUrl := .Values.credentials.apiBaseUrl }}
{{- $configMode := .Values.credentials.configMode }}
{{- if and (not .Values.cloudflare.existingSecret) (or $accountId $token) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway-cloudflare.secretName" . }}
  namespace: {{ include "gateway-cloudflare.controllerNamespace" . }}
  labels:
    {{- include "gateway-cloudflare.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $accountId }}
  ACCOUNT_ID: {{ $accountId | quote }}
  {{- end }}
  {{- if $token }}
  TOKEN: {{ $token | quote }}
  {{- end }}
  {{- if $apiBaseUrl }}
  API_BASE_URL: {{ $apiBaseUrl | quote }}
  {{- end }}
  {{- if $configMode }}
  CONFIG_MODE: {{ $configMode | quote }}
  {{- end }}
{{- end }}
