{{- if and (not .Values.cloudflare.existingSecret) (or .Values.cloudflare.accountId .Values.cloudflare.apiToken) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway-cloudflare.secretName" . }}
  namespace: {{ include "gateway-cloudflare.controllerNamespace" . }}
  labels:
    {{- include "gateway-cloudflare.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.cloudflare.accountId }}
  ACCOUNT_ID: {{ .Values.cloudflare.accountId | quote }}
  {{- end }}
  {{- if .Values.cloudflare.apiToken }}
  TOKEN: {{ .Values.cloudflare.apiToken | quote }}
  {{- end }}
{{- end }}

