apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-codezero
  labels:
    {{- include "codezero.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_HOST: {{ include "codezero.postgresHost" . | quote }}
  POSTGRES_PORT: "5432"
  INITIAL_ROOT_PASSWORD: {{ .Values.admin.password | quote }}
  INITIAL_ROOT_MAIL: {{ .Values.admin.email | quote }}
  {{- if .Values.runtime.aquila.sagittariusToken }}
  AQUILA_SAGITTARIUS_TOKEN: {{ .Values.runtime.aquila.sagittariusToken | quote }}
  {{- end }}
