# StorageClass for Local Path Provisioner
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
    {{- include "storage-local-path.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.storageClass.isDefault }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
provisioner: rancher.io/local-path
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
