apiVersion: v2
name: gateway-cloudflare
description: Cloudflare Tunnel Gateway for Kubernetes Gateway API
type: application
version: 1.0.0
appVersion: '0.8.1'
keywords:
  - gateway-api
  - cloudflare
  - tunnel
  - zero-trust
  - ingress
home: https://cnap.tech
sources:
  - https://github.com/cnap-tech/charts
  - https://github.com/pl4nty/cloudflare-kubernetes-gateway
  - https://github.com/lwijnsma/cloudflare-kubernetes-gateway
