{{- if .Values.persistence.enabled }}
{{- range .Values.persistence.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" $ }}-{{ .name }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  accessModes:
    - {{ .accessMode | default "ReadWriteOnce" }}
  {{- if .storageClassName }}
  storageClassName: {{ .storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size | default "1Gi" }}
{{- end }}
{{- end }}
